title: Aleksei Ivantsov
logo: "/images/photo.jpg?raw=true"
description: >
  Creative and driven Android Developer with collateral knowledge: Python, SQL, C/C++ and etc.
  <br><br>
  My life motto is "ipsa scientia potestas est".
  <br><br>
  <a href="https://www.linkedin.com/in/aleksei-ivantsov-237b601/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158894575-1
permalink: /404.md
